=== mcparfer/ASIR_HTML_XML_CSS/notes/ejercicios_xml/ejercicio7/cartelera.dtd
<!ELEMENT CARTELERA (PELÍCULA*)>
<!ELEMENT PELÍCULA (TÍTULO, TITULOORIGINAL?, NACIONALIDAD, GÉNERO, (CLASIFICACIÓN | SINCLASIFICAR), SINOPSIS, DIRECTOR, REPARTO, WEB?, CARTEL?) >

<!ELEMENT TÍTULO (#PCDATA)>
<!ELEMENT TITULOORIGINAL (#PCDATA)>
<!ELEMENT NACIONALIDAD (#PCDATA)>
<!ELEMENT GÉNERO (#PCDATA)>
<!ELEMENT CLASIFICACIÓN EMPTY>
<!ELEMENT SINCLASIFICAR EMPTY>
<!ELEMENT SINOPSIS (#PCDATA)>
<!ELEMENT DIRECTOR (#PCDATA)>
<!ELEMENT REPARTO (ACTOR+)>
<!ELEMENT ACTOR (#PCDATA)>
<!ELEMENT WEB (#PCDATA)>
<!ELEMENT CARTEL (#PCDATA)>    

<!ATTLIST PELÍCULA CÓDIGO ID #REQUIRED>
<!ATTLIST PELÍCULA DURACIÓN CDATA #REQUIRED>
<!ATTLIST PELÍCULA AÑO CDATA #IMPLIED>
<!ATTLIST CLASIFICACIÓN EDAD (8 | 12 | 16 | 18 | TP) #REQUIRED>

=== mcparfer/ASIR_HTML_XML_CSS/notes/ejercicios_xml/ejercicio7/cartelera.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE CARTELERA SYSTEM "cartelera.dtd">

<CARTELERA> 
    <PELÍCULA CÓDIGO="P1" DURACIÓN="152" AÑO="2002"> 
        <TÍTULO>AQUELLAS JUERGAS UNIVERSITARIAS</TÍTULO> 
        <TITULOORIGINAL>OLD SCHOOL</TITULOORIGINAL> 
        <NACIONALIDAD>ESTADOS UNIDOS</NACIONALIDAD> 
        <GÉNERO>COMEDIA</GÉNERO> 
        <CLASIFICACIÓN EDAD="TP"/> 
        <SINOPSIS> 
            MITCH, FRANK Y BEANIE SON TRES AMIGOS TREINTAÑEROS CUYAS VIDAS NO SON EXACTAMENTE LO QUE ESPERABAN. MITCH TIENE UNA NOVIA NINFÓMANA QUE SE METE EN LA CAMA CON EL PRIMERO QUE AGARRA. FRANK SE HA CASADO Y SU MATRIMONIO NADA 
            TIENE QUE VER CON LAS JUERGAS SALVAJES QUE ORGANIZABAN AÑOS ATRÁS. Y BEANIE ES 
            UN PADRE DE FAMILIA QUE SE MUERE POR RECUPERAR SU ALOCADA JUVENTUD. PERO LAS COSAS CAMBIAN CUANDO BEANIE SUGIERE QUE CREEN SU PROPIA FRATERNIDAD, EN LA NUEVA CASA QUE MITCH TIENE JUNTO AL CAMPUS DE LA UNIVERSIDAD. UNA OCASIÓN PARA REVIVIR TIEMPOS GLORIOSOS, HACER NUEVOS AMIGOS Y DE VOLVER A SUS VIEJAS, SALVAJES Y DESMADRADAS JUERGAS DE ESTUDIANTES. 
        </SINOPSIS> 
        <DIRECTOR>TODD PHILIPS</DIRECTOR> 
        <REPARTO> 
            <ACTOR>LUKE WILSON</ACTOR> 
            <ACTOR>WILL FARREL</ACTOR> 
            <ACTOR>VINCE VAUGHN</ACTOR> 
        </REPARTO> 
        <WEB>HTTP://WWW.UIP.ES</WEB> 
        <CARTEL>CARATULAS/AQUELLAS JUERGAS.JPG</CARTEL> 
    </PELÍCULA> 
    <PELÍCULA CÓDIGO="P17" DURACIÓN="06"> 
        <TÍTULO>EL ORO DE MOSCÚ</TÍTULO> 
        <NACIONALIDAD>ESPAÑA</NACIONALIDAD> 
        <GÉNERO>COMEDIA</GÉNERO> 
        <SINCLASIFICAR/> 
        <SINOPSIS> 
            POR UNA EXTRAÑA COINCIDENCIA DEL DESTINO, ALGUIEN RECIBE UNA INFORMACIÓN EXTRACONFIDENCIAL DE UN ANCIANO EN SUS ÚLTIMOS SEGUNDOS DE VIDA: EL SECRETO MEJOR GUARDADO DE LA HISTORIA. EL RECEPTOR, UN TRABAJADOR DE HOSPITAL, SE LO COMUNICA SECRETAMENTE A UN SUPUESTO AMIGO. AMBOS INICIAN UNA AVENTURA ROCAMBOLESCA Y LLENA DE MISTERIO. ANTE LA INUTILIDAD DE SUS INTENTOS Y MUY A 
            SU PESAR, TIENEN QUE RECURRIR A OTRAS PERSONAS QUE ASÍ MISMO VAN CAYENDO EN EL POZO SIN FONDO QUE CONLLEVA DESCIFRAR EL ENIGMA. 
        </SINOPSIS> 
        <DIRECTOR>JESÚS BONILLA</DIRECTOR> 
        <REPARTO> 
            <ACTOR>JESÚS BONILLA</ACTOR> 
            <ACTOR>SANTIAGO SEGURA</ACTOR> 
            <ACTOR>ALFREDO LANDA</ACTOR> 
            <ACTOR>CONCHA VELASCO</ACTOR> 
            <ACTOR>ANTONIO RESINES</ACTOR> 
            <ACTOR>GABINO DIEGO, MARÍA BARRANCO</ACTOR> 
            <ACTOR>MARÍA BARRANCO</ACTOR> 
        </REPARTO> 
    </PELÍCULA> 
</CARTELERA>
