<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE FACTURA [
    <!ELEMENT FACTURAS (FACTURA*)>
    <!ELEMENT FACTURA (DATOSEMPRESA, DATOSCLIENTE, DATOSFACTURA)>

    <!ELEMENT DATOSEMPRESA (NOMBRE, DIRECCION, CIF, TELEFONO, FAX)>
		<!ELEMENT NOMBRE (#PCDATA)>
		<!ELEMENT DIRECCION (CALLE, POBLACION, PROVINCIA?)>
			<!ELEMENT CALLE (#PCDATA)>
			<!ELEMENT POBLACION (#PCDATA)>
			<!ELEMENT PROVINCIA (#PCDATA)>
		<!ELEMENT CIF (#PCDATA)>
		<!ELEMENT TELEFONO (#PCDATA)>
		<!ELEMENT FAX (#PCDATA)>
    <!ELEMENT DATOSCLIENTE (NOMBRE, DIRENV, POBLACION, PROVINCIA)>
		<!ELEMENT DIRECCION (CALLE, POBLACION, PROVINCIA?)>
    <!ELEMENT DATOSFACTURA (DATOS*, BASE, CUOTAIVA, TOTAL)>
		<!ELEMENT DATOS (REFERENCIA, DESCRIPCION, CANTIDAD, PRECIO, IMPORTE)>
			<!ELEMENT REFERENCIA (#PCDATA)>
			<!ELEMENT DESCRIPCION (#PCDATA)>
			<!ELEMENT CANTIDAD (#PCDATA)>
			<!ELEMENT PRECIO (#PCDATA)>
			<!ELEMENT IMPORTE (#PCDATA)>
		<!ELEMENT BASE (#PCDATA)>
		<!ELEMENT CUOTAIVA (#PCDATA)>
		<!ELEMENT TOTAL (#PCDATA)>

    <!ATTLIST FACTURA N_FAC ID #REQUIRED>
    <!ATTLIST POBLACION COD_POSTAL CDATA #REQUIRED>
    <!ATTLIST DATOSCLIENTE N_CLI ID #REQUIRED>
    <!ATTLIST DATOSFACTURA FECHA CDATA #REQUIRED>
    <!ATTLIST DATOSFACTURA N_PEDIDO ID #REQUIRED>
    <!ATTLIST DATOSFACTURA F_PAGO (EFECTIVO|TARJETA) #REQUIRED>
    <!ATTLIST DATOSFACTURA MONEDA CDATA #REQUIRED>
    <!ATTLIST PRECIO IVA CDATA #REQUIRED>
    <!ATTLIST BASE IVA CDATA #REQUIRED>
]>

<FACTURAS>
  <FACTURA N_FAC="999">
    <DATOSEMPRESA>
      <NOMBRE>EQUIPOS DIGITALES S.L.</NOMBRE>
      <DIRECCION>
      <CALLE>AV. VALLADOLID</CALLE>
      <POBLACION COD_POSTAL="28043">MADRID</POBLACION>
    </DIRECCION>
      <CIF>Q-9876543</CIF>
      <TELEFONO>917776688</TELEFONO>
    <FAX>917776688</FAX>
    </DATOSEMPRESA>
    <DATOSCLIENTE N_CLI="879">
      <NOMBRE>DARIO, BUENO GUTIERREZ</NOMBRE>
    <DIRECCION>
      <CALLE>AV. OPORTO Nº7 4ºD</CALLE>
      <POBLACION COD_POSTAL="28043">MADRID</POBLACION>
      <PROVINCIA>MADRID</PROVINCIA>
    </DIRECCION>
    </DATOSCLIENTE>    
    <DATOSFACTURA FECHA="12-01-2005" N_PEDIDO="731" F_PAGO= "EFECTIVO" MONEDA="EUROS">
      <DATOS>
          <REFERENCIA>MII93000F/8</REFERENCIA>
          <DESCRIPCION>MICRO PENTIUM IV 3000MHZ FB800</DESCRIPCION>
          <CANTIDAD>1</CANTIDAD>
          <PRECIO IVA="16">230</PRECIO>
          <IMPORTE>266,80</IMPORTE>
      </DATOS>
      <DATOS>
          <REFERENCIA>MB8QDIP4</REFERENCIA>
          <DESCRIPCION>PLACA BASE QDI P4</DESCRIPCION>
          <CANTIDAD>1</CANTIDAD>
          <PRECIO IVA="16">180</PRECIO>
          <IMPORTE>208,80</IMPORTE>
      </DATOS>
      <DATOS>
          <REFERENCIA>MEDD512M32</REFERENCIA>
          <DESCRIPCION>DIMM DDR 512MB 3200</DESCRIPCION>
          <CANTIDAD>2</CANTIDAD>
          <PRECIO IVA="16">40</PRECIO>
          <IMPORTE>92,80</IMPORTE>
      </DATOS>
      <DATOS>
          <REREFERENCIAF>HD250GSA7</REFERENCIA>
          <DESCRIPCION>DISCO DURO 250GB S-ATA 7200</DESCRIPCION>
          <CANTIDAD>4</CANTIDAD>
          <PRECIO IVA="16">120</PRECIO>
          <IMPORTE>556,80</IMPORTE>
      </DATOS>
      <BASE IVA="16">970,00</BASE>
      <CUOTAIVA>155,20</CUOTAIVA>
      <TOTAL>1125,20</TOTAL>
    </DATOSFACTURA>
  </FACTURA>
</FACTURAS>