<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE AULA [
  <!ELEMENT AULA (ALUMNO*)>
  <!ELEMENT ALUMNO (NOMBRE, APELLIDOS, SEXO?, FECHANAC, DIRECCION, TELEFONO, NOTAMEDIA)>

  <!ELEMENT NOMBRE (#PCDATA)>
  <!ELEMENT APELLIDOS (#PCDATA)>
  <!ELEMENT SEXO (#PCDATA)>
  <!ELEMENT FECHANAC (DIA, MES, ANO)>
    <!ELEMENT DIA (#PCDATA)>
    <!ELEMENT MES (#PCDATA)>
    <!ELEMENT ANO (#PCDATA)>
  <!ELEMENT DIRECCION (#PCDATA)>        
  <!ELEMENT TELEFONO (#PCDATA)>        
  <!ELEMENT NOTAMEDIA (#PCDATA)>                    

  <!ATTLIST NOMBRE DNI ID #REQUIRED>
  <!ATTLIST FECHANAC ZODIACO  (ARIES | TAURO | GEMINIS | CANCER | LEO | VIRGO | LIBRA | ESCORPIO | SAGITARIO | CAPRICORNIO | ACUARIO | PISCIS) #REQUIRED>
  <!ATTLIST TELEFONO TIPO (FIJO | MOVIL)>       
]>

<AULA>
    <ALUMNO DNI="">
        <NOMBRE></NOMBRE>
        <APELLIDOS></APELLIDOS>
        <SEXO></SEXO>
        <FECHANAC ZODIACO="">
            <DIA></DIA>
            <MES></MES>
            <ANO></ANO>
        </FECHANAC>
        <DIRECCION></DIRECCION>
        <TELEFONO TIPO=""></TELEFONO>
        <NOTAMEDIA></NOTAMEDIA>        
    </ALUMNO>
</AULA>