<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE CARTELERA [
  <!ELEMENT CARTELERA (PELICULA*)>
  <!ELEMENT PELICULA (TITULO, NACIONALIDAD, DURACION, DIRECTOR, ACTORES, DESCRIPCION)>

  <!ELEMENT TITULO (#PCDATA)>
  <!ELEMENT NACIONALIDAD (#PCDATA)>
  <!ELEMENT DURACION (#PCDATA)>
  <!ELEMENT DIRECTOR (#PCDATA)>
  <!ELEMENT ACTORES (ACTOR+)>
    <!ELEMENT ACTOR (NOMBRE, APELLIDOS)>
      <!ELEMENT NOMBRE (#PCDATA)>
      <!ELEMENT APELLIDOS (#PCDATA)>
  <!ELEMENT DESCRIPCION (#PCDATA)>

  <!ATTLIST PELICULAS ESTRENO CDATA #IMPLIED>
  <!ATTLIST ACTOR TIPO (PRINCIPAL | REPARTO)>  
]>


<CARTELERA>
    <PELICULA ESTRENO="">
        <TITULO></TITULO>
        <NACIONALIDAD></NACIONALIDAD>
        <DURACION></DURACION>
        <DIRECTOR></DIRECTOR>
        <ACTORES>
            <ACTOR TIPO="">
                <NOMBRE></NOMBRE>
                <APELLIDOS></APELLIDOS>
            </ACTOR>
        </ACTORES>
        <DESCRIPCION></DESCRIPCION>
    </PELICULA>
</CARTELERA>
