<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE LIGA [
  <!ELEMENT LIGA (PARTIDO*)>
  <!ELEMENT PARTIDO (LOCAL, VISITANTE)>

  <!ELEMENT LOCAL (#PCDATA)>
  <!ELEMENT VISITANTE (#PCDATA)>
  
  <!ATTLIST LOCAL GOLES CDATA #REQUIRED>
  <!ATTLIST VISITANTE GOLES CDATA #REQUIRED>
]>

<LIGA>
  <PARTIDO>
    <LOCAL GOLES="0">NOTTINGHAM PRESA</LOCAL>
    <VISITANTE GOLES="1">INTER DE MITENTE</VISITANTE>
  </PARTIDO>
  <PARTIDO>
    <LOCAL GOLES="3">VODKA JUNIORS</LOCAL>
    <VISITANTE GOLES="3">SPARTA DA RISA</VISITANTE>
  </PARTIDO>
  <PARTIDO>
    <LOCAL GOLES="4">WATER DE MÃšNICH</LOCAL>
    <VISITANTE GOLES="2">ESTEAUA ES DEL GRIFO</VISITANTE>
  </PARTIDO>
</LIGA>
