<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE TVSCHEDULE [
    <!ELEMENT TVSCHEDULE (CHANNEL+)>
        <!ELEMENT CHANNEL (BANNER, DAY+)>
        <!ELEMENT BANNER (#PCDATA)>
        <!ELEMENT DAY (DATE, (HOLIDAY | PROGRAMSLOT+)+)>
            <!ELEMENT HOLIDAY (#PCDATA)>
            <!ELEMENT DATE (#PCDATA)>
            <!ELEMENT PROGRAMSLOTS (PROGRAMSLOT)>
            <!ELEMENT PROGRAMSLOT (TIME, TITLE, DESCRIPTION?)>
                <!ELEMENT TIME (#PCDATA)>
                <!ELEMENT TITLE (#PCDATA)>
                <!ELEMENT DESCRIPTION (#PCDATA)>

        <!ATTLIST TVSCHEDULE NAME CDATA #REQUIRED>
        <!ATTLIST CHANNEL CHAN CDATA #REQUIRED>
        <!ATTLIST PROGRAMSLOT VTR CDATA #IMPLIED>
        <!ATTLIST TITLE RATING CDATA #IMPLIED>
        <!ATTLIST TITLE LANGUAGE CDATA #IMPLIED>
]>

<TVSCHEDULE NAME="">
    <CHANNEL CHAN="">
        <BANNER></BANNER>
        <DAY>
            <DATE></DATE>
            <HOLIDAY></HOLIDAY>
        </DAY>
    </CHANNEL>
    <CHANNEL CHAN="">
        <BANNER></BANNER>
        <DAY>
            <DATE></DATE>
            <HOLIDAY></HOLIDAY>
            <PROGRAMSLOTS >
                <PROGRAMSLOT VTR="">
                    <TIME></TIME>
                    <TITLE RATING=""></TITLE>
                    <DESCRIPTION></DESCRIPTION>
                </PROGRAMSLOT>
            </PROGRAMSLOTS>
        </DAY>
    </CHANNEL>
</TVSCHEDULE>
