<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE LIGA [
  <!ELEMENT LIGA (PARTIDO*)>
  <!ELEMENT PARTIDO (LOCAL, VISITANTE)>

  <!ELEMENT LOCAL (NOMBRE, GOLES)>
  <!ELEMENT VISITANTE (NOMBRE, GOLES)>
    <!ELEMENT NOMBRE (#PCDATA)>
    <!ELEMENT GOLES (#PCDATA)>
]>

<LIGA>
  <PARTIDO>
    <LOCAL>
      <NOMBRE>NOTTINGHAM PRESA</NOMBRE>
      <GOLES>0</GOLES>
    </LOCAL>
    <VISITANTE>
      <NOMBRE>INTER DE MITENTE</NOMBRE>
      <GOLES>1</GOLES>
    </VISITANTE>
  </PARTIDO>
  <PARTIDO>
    <LOCAL>
      <NOMBRE>VODKA JUNIORS</NOMBRE>
      <GOLES>3</GOLES>
    </LOCAL>
    <VISITANTE>
      <NOMBRE>SPARTA DA RISA</NOMBRE>
      <GOLES>3</GOLES>
    </VISITANTE>
  </PARTIDO>
  <PARTIDO>
    <LOCAL>
      <NOMBRE>WATER DE MÃšNICH</NOMBRE>
      <GOLES>4</GOLES>
    </LOCAL>
    <VISITANTE>
      <NOMBRE>ESTEAUA ES DEL GRIFO</NOMBRE>
      <GOLES>2</GOLES>
    </VISITANTE>
  </PARTIDO>
</LIGA>

