<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE COMPETICION [
  <!ELEMENT COMPETICION (EQUIPO*)>
  <!ELEMENT EQUIPO (NOMBREEQUIPO, NACIONALIDAD, PRESUPUESTO?, (NORMAL | DOBLE), SWEEPERS, PISTA, FECHAFUNDACION)>

  <!ELEMENT NOMBREEQUIPO (#PCDATA)>
  <!ELEMENT NACIONALIDAD (#PCDATA)>
  <!ELEMENT PRESUPUESTO (#PCDATA)>
  <!ELEMENT NORMAL EMPTY>
  <!ELEMENT DOBLE EMPTY>
  <!ELEMENT SWEEPERS (SWEEPER+)>
    <!ELEMENT SWEEPER (NOMBRE, APELLIDOS, EDAD, SEXO)>
      <!ELEMENT NOMBRE (#PCDATA)>
      <!ELEMENT APELLIDOS (#PCDATA)>
      <!ELEMENT EDAD (#PCDATA)>
      <!ELEMENT SEXO (#PCDATA)>
  <!ELEMENT PISTA (NOMBREPISTA, ASIENTOS, DIRECCION)>
    <!ELEMENT NOMBREPISTA (#PCDATA)>
    <!ELEMENT ASIENTOS (#PCDATA)>
    <!ELEMENT DIRECCION (CALLE, NUMERO, POBLACION)>
      <!ELEMENT CALLE (#PCDATA)>
      <!ELEMENT NUMERO (#PCDATA)>
      <!ELEMENT POBLACION (CP?, PROVINCIA)>
        <!ELEMENT CP (#PCDATA)>
        <!ELEMENT PROVINCIA (#PCDATA)>
  <!ELEMENT FECHAFUNDACION (DIA, MES, ANO)>
    <!ELEMENT DIA (#PCDATA)>
    <!ELEMENT MES (#PCDATA)>
    <!ELEMENT ANO (#PCDATA)>

  <!ATTLIST COMPETICION ANO CDATA #IMPLIED>
  <!ATTLIST SWEEPER DNI ID #REQUIRED>
]>

<COMPETICION ANO="">
    <EQUIPO>
        <NOMBREEQUIPO></NOMBREEQUIPO>
        <NACIONALIDAD></NACIONALIDAD>
        <PRESUPUESTO></PRESUPUESTO>
        <NORMAL/>
        <SWEEPERS>
            <SWEEPER DNI="">
                <NOMBRE></NOMBRE>
                <APELLIDOS></APELLIDOS>
                <EDAD></EDAD>
                <SEXO></SEXO>
            </SWEEPER>
        </SWEEPERS>
        <PISTA>
            <NOMBREPISTA></NOMBREPISTA>
            <ASIENTOS></ASIENTOS>
            <DIRECCION>
                <CALLE></CALLE>
                <NUMERO></NUMERO>
                <POBLACION>
                    <CP></CP>
                    <PROVINCIA></PROVINCIA>
                </POBLACION>
            </DIRECCION>
        </PISTA>
        <FECHAFUNDACION>
            <DIA></DIA>
            <MES></MES>
            <ANO></ANO>
        </FECHAFUNDACION>
    </EQUIPO>
</COMPETICION>
